apiVersion: v2
name: prefect-server
description: Prefect Server application bundle
type: application
home: https://github.com/PrefectHQ
version: 0.0.0
appVersion: "latest"
maintainers:
  - name: madkinsz
    email: michael@prefect.io
sources:
  - https://github.com/PrefectHQ/server
dependencies:
- name: postgresql
  version: "~9.3.2"
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.useSubChart
