{{- if .Values.agent.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prefect-server.nameField" (merge (dict "component" "agent") .) }}
  labels: 
    {{- include "prefect-server.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
  annotations:
    {{- merge .Values.agent.annotations .Values.annotations | toYaml | nindent 4 }}
spec:
  replicas: {{ .Values.agent.replicas }}
  {{- with .Values.agent.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prefect-server.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        {{- include "prefect-server.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: agent
    spec:
    {{- if .Values.agent.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.agent.image.pullSecrets | nindent 8 }}
    {{- else if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "prefect-server.serviceAccountName" . }}
      {{- with .Values.agent.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: agent
        {{- with .Values.agent.podSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        image: "{{ .Values.agent.image.name }}:{{ .Values.agent.image.tag | default .Values.prefectVersionTag }}"
        imagePullPolicy: {{ .Values.agent.image.pullPolicy  }}
        command:
          - bash
          - "-c"
          - "prefect agent kubernetes start"
        env:
          - name: PREFECT__CLOUD__API
            value: {{ include "prefect-server.apollo-api-url" . }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
          - name: IMAGE_PULL_SECRETS
            value: {{ .Values.agent.job.imagePullSecrets | join "," | quote }}
          - name: PREFECT__CLOUD__AGENT__LABELS
            value: {{ .Values.agent.prefectLabels | toJson | quote }}
          - name: JOB_MEM_REQUEST
            value: {{ .Values.agent.job.resources.requests.memory | quote }}
          - name: JOB_MEM_LIMIT
            value: {{ .Values.agent.job.resources.limits.memory | quote }}
          - name: JOB_CPU_REQUEST
            value: {{ .Values.agent.job.resources.requests.cpu | quote }}
          - name: JOB_CPU_LIMIT
            value: {{ .Values.agent.job.resources.limits.cpu | quote }}
          - name: IMAGE_PULL_POLICY
            value: {{ .Values.agent.job.imagePullPolicy | quote }}
          - name: SERVICE_ACCOUNT_NAME
            value: {{ include "prefect-server.serviceAccountName" . }}
          - name: PREFECT__BACKEND
            value: server
          - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
            value: http://0.0.0.0:8080
          {{- with .Values.agent.env }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 40
        {{- with .Values.agent.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
