apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prefect-server.nameField" (merge (dict "component" "graphql") .) }}
  labels: 
    {{- include "prefect-server.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: graphql
  annotations:
    {{- merge .Values.graphql.annotations .Values.annotations | toYaml | nindent 4 }}
spec:
  replicas: {{ .Values.graphql.replicas }}
  selector:
    matchLabels:
      {{- include "prefect-server.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: graphql
  template:
    metadata:
      labels:
        {{- include "prefect-server.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: graphql
    spec:
      imagePullSecrets: {{ concat .Values.graphql.image.pullSecrets .Values.imagePullSecrets | uniq | toJson }}
      serviceAccountName: {{ include "prefect-server.serviceAccountName" . }}
      {{- with .Values.graphql.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: db-upgrade
          {{- with .Values.graphql.securityContext -}}          
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.graphql.image.name }}:{{ .Values.graphql.image.tag |  default .Values.prefectVersionTag }}"
          imagePullPolicy: {{ .Values.graphql.image.pullPolicy  }}
          command:
            - "bash"
            - "-c"
            - "/usr/local/bin/prefect-server database upgrade --yes"
          env:
            - name: PREFECT_SERVER__DATABASE__CONNECTION_URL
              value: {{ include "prefect-server.postgres-connstr" . }}
            - name: PGPASSWORD
              valueFrom:
                {{- include "prefect-server.postgres-secret-ref" . | nindent 16 }}
            - name: PREFECT_SERVER__HASURA__HOST
              value: {{ include "prefect-server.hasura-hostname" . }}
            {{- (include "prefect-server.envConfig" .) | nindent 12 }}
          {{- with .Values.graphql.init.resources -}}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        - name: graphql
          {{- with .Values.graphql.securityContext -}}          
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.graphql.image.name }}:{{ .Values.graphql.image.tag |  default .Values.prefectVersionTag }}"
          imagePullPolicy: {{ .Values.graphql.image.pullPolicy  }}
          command: 
            - bash 
            - "-c" 
            - "python src/prefect_server/services/graphql/server.py"
          env:
            - name: PREFECT_SERVER_DB_CMD
              value: "echo 'DATABASE MIGRATIONS SKIPPED'"
            - name: PREFECT_SERVER__DATABASE__CONNECTION_URL
              value: {{ include "prefect-server.postgres-connstr" . }}
            - name: PGPASSWORD
              valueFrom:
                {{- include "prefect-server.postgres-secret-ref" . | nindent 16 }}            
            - name: PREFECT_SERVER__HASURA__HOST
              value: {{ include "prefect-server.hasura-hostname" . }}
            {{- (include "prefect-server.envConfig" .) | nindent 12 }}
          ports:
            - name: http
              containerPort: 4201
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          {{- with .Values.graphql.resources -}}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.graphql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.graphql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.graphql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
